name: Registry image

on:
  push:
    branches: ["main"]

jobs:
  login-push-usercreate:
    uses: ./.github/workflows/login-build-push.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME }}

  ec2-cd-userdomain:
    needs: login-push-usercreate
    uses: ./.github/workflows/setupDocker.yml
    secrets:
      ec2_host: ${{ secrets.AWS_HOST_IP }}
      ec2_key: ${{ secrets.AWS_HOST_KEY }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME }}